# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1165e8872956e2ab24684f33209c2671d790696411e2571c394f72788c9bc762ca3f1d73635976d91eb19f7e1c549ab2beaccc146544f4ce6374347268c1782

test:
  secret_key_base: 0259f408ab33d6778311e1867cba2a1078b27e75de09c9aa4b7d3f25ab3e7a18fa57addff040894b93c7ee2a9498bb17935891bbab187e01a580cc1aa5782349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
